name: Build All Devices

on:
  workflow_dispatch:
    inputs:
      devices:
        description: 'Device list (comma-separated or "all")'
        required: false
        default: "all"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        device: ${{ 
          inputs.devices == 'all' 
          && fromJson('["10T","11","12","12r","13","Ace2","Ace2Pro","Ace3Pro","Ace3V","Ace5","Ace5Pro","AcePro","PadPro"]') 
          || fromJson(format('["{0}"]', replace(inputs.devices, ',', '","'))) 
        }}
    
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup Toolchain
      uses: android-actions/setup-ndk@v1
      with:
        ndk-version: r25b

    - name: Build
      run: |
        make O=out_${{ matrix.device }} clean
        make O=out_${{ matrix.device }} ${{ matrix.device }}_defconfig
        make -j$(nproc) O=out_${{ matrix.device }}

    - uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.device }}-kernel
        path: out_${{ matrix.device }}/arch/arm64/boot/Image.gz-dtb
